trigger:
  - main

jobs:
- job: 'BuildFigmaSharpMac'

  pool:
    vmImage: 'macOS-10.15'

  variables:
    - name: SOURCES_DIRECTORY
      value: $(Build.SourcesDirectory)
    - name: SOURCE_VERSION
      value: $(Build.SourceVersion)
    - name: ARTIFACT_STAGING_DIRECTORY
      value: $(Build.ArtifactStagingDirectory)

  steps:
    - task: Bash@3
      name: 'BuildMacApp'
      inputs:
        targetType: 'inline'
        script: |
          msbuild tools/FigmaSharpApp/FigmaSharpApp.csproj /p:"Configuration=Release;Platform=AnyCPU" /restore

    - task: Bash@3
      name: 'BuildMacExtension'
      inputs:
        targetType: 'inline'
        script: |
          msbuild tools/MonoDevelop.Figma/MonoDevelop.Figma.csproj /p:Configuration=Release /p:InstallAddin=true /restore

    - task: ArchiveFiles@2
      name: 'PrepareMacApp'
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/tools/FigmaSharpApp/bin/Release/FigmaSharpApp.app'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/FigmaSharpApp-$(Build.SourceVersion).zip'
        replaceExistingArchive: true

    - task: Bash@3
      name: 'PrepareMacExtension'
      inputs:
        targetType: 'inline'
        script: |
          mv ${SOURCES_DIRECTORY}/tools/MonoDevelop.Figma/bin/Release/*/*.mpack ${SOURCES_DIRECTORY}/FigmaSharpExtension-${SOURCE_VERSION}.mpack

    - task: CopyFiles@2
      name: 'CopyMacExtension'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: 'FigmaSharpExtension-*.mpack'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      name: 'PublishMacApp'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/FigmaSharpApp-$(Build.SourceVersion).zip'
        ArtifactName: 'MacBuilds'
        publishLocation: 'Container'

    - task: PublishBuildArtifacts@1
      name: 'PublishMacExtension'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/FigmaSharpExtension-$(Build.SourceVersion).mpack'
        ArtifactName: 'MacBuilds'
        publishLocation: 'Container'

    - task: GitHubRelease@1
      name: 'PublishToGitHub'
      inputs:
        gitHubConnection: 'github.com_hbons'
        repositoryName: '$(Build.Repository.Name)'
        action: 'create'
        target: '$(Build.SourceVersion)'
        tagSource: 'gitTag'
        addChangeLog: false
